# Generated by Django 5.0.6 on 2024-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="liked_tags",
            field=models.ManyToManyField(related_name="liked_by", to="blog.tag"),
        ),
    ]
