# Generated by Django 5.0.6 on 2024-06-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_liked_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='liked_tags',
        ),
    ]
