name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - deploy_pythonanywhere

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Pull latest code on PythonAnywhere
        run: |
          curl -X POST \
              -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
              -d 'input=git pull%0A' \
              https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/
    
      - name: Reload webapp
        run: |
          curl -X POST \
              -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
              https://www.pythonanywhere.com//api/v0/user/${{ secrets.USERNAME }}/webapps/${{ secrets.DOMAIN_NAME }}/reload
