name: Deploy to PythonAnywhere

on:
  push:
    branches: [ "deploy_pythonanywhere" ]
  pull_request:
    branches: [ "deploy_pythonanywhere" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@v1.0.0
        with:
          host: 'www.pythonanywhere.com' # or 'www.eu.pythonanywhere.com' depending on your server location
          username: ${{ secrets.USERNAME }}
          api_token: ${{ secrets.API_TOKEN }}
          domain_name: ${{ secrets.DOMAIN_NAME }}
          console_id:  ${{ secrets.CONSOLE_ID }}
          virtual_env: ${{ secrets.VIRTUAL_ENV }}
          directory: ${{ secrets.DIRECTORY }}

      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.USERNAME }}
          api-token: ${{ secrets.API_TOKEN }}
          domain-name: ${{ secrets.DOMAIN_NAME }}
