name: Deploy to PythonAnywhere

on:
  push:
    branches: [ "deploy_pythonanywhere" ]
  pull_request:
    branches: [ "deploy_pythonanywhere" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Pull latest code on PythonAnywhere
        run: |
          curl -X POST \
              -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
              -d 'input=cd /home/engrhaseebjan/ChatGPT-BLOGGING-A-Django-Application %0Agit pull %0A' \
              https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/{{ secrets.CONSOLE_ID }}/send_input/
    
      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'www.pythonanywhere.com'
          username: ${{ secrets.USERNAME }}
          api-token: ${{ secrets.API_TOKEN }}
          domain-name: ${{ secrets.DOMAIN_NAME }}
