name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-django
  
      - name: Apply migrations
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python manage.py makemigrations
          python manage.py migrate
          
      - name: Lint with Pylint
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pylint --load-plugins pylint_django --rcfile=.pylintrc $(find . -name '*.py' ! -path "*/migrations/*")
  
      - name: Run Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python manage.py test

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory using cd.
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=cd /home/${{ secrets.USERNAME }}/ChatGPT-BLOGGING-A-Django-Application%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/
              
      - name: Checkout branch to main
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=git checkout main%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: Pull latest code 
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=git pull%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: make migrations
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=python manage.py makemigrations%0Apython manage.py makemigrations blog%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/
 
      - name: Migrate
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=python manage.py migrate%0Apython manage.py migrate blog%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: Reload webapp
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/webapps/${{ secrets.DOMAIN_NAME }}/reload
