name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory using cd.
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=cd /home/${{ secrets.USERNAME }}/ChatGPT-BLOGGING-A-Django-Application%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/
              
      - name: Checkout branch to main
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=git checkout main%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: Pull latest code 
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=git pull%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: make migrations
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=python manage.py makemigrations%0Apython manage.py makemigrations blog%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/
 
      - name: Migrate
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            -d 'input=python manage.py migrate%0Apython manage.py migrate blog%0A' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/consoles/${{ secrets.CONSOLE_ID }}/send_input/

      - name: Reload webapp
        run: |
          curl -X POST \
            -H 'Authorization: Token ${{ secrets.API_TOKEN }}' \
            https://www.pythonanywhere.com/api/v0/user/${{ secrets.USERNAME }}/webapps/${{ secrets.DOMAIN_NAME }}/reload
