name: Django CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Check API Key Length
      run: echo "API Key Length: ${#OPENAI_API_KEY}"
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pylint-django

    - name: Apply migrations
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Lint with Pylint
      run: |
        pylint --load-plugins pylint_django --rcfile=.pylintrc $(find . -name '*.py' ! -path "*/migrations/*")

    - name: Run Tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python manage.py test
